import 'dart:io';
import 'dart:math';

import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';

/// Identifies this *installation* — not this device, and not this account.
///
/// A random value generated on first launch and kept in a file. Deliberately
/// not a hardware identifier: Android ID and the advertising ID are restricted
/// under Play policy, cannot be reset by the user, and would survive an account
/// deletion that is supposed to erase everything. This one is regenerated by a
/// reinstall and is deleted along with the account.
///
/// It **must** survive signing out. That is what lets the backend show that two
/// accounts belong to the same phone when someone switches between them, which
/// a session-scoped value could never do.
class DeviceIdentity {
  DeviceIdentity._();

  static const _fileName = 'install_id';

  static String _installId = '';

  /// The install id, or an empty string before [ensure] has run. Callers treat
  /// empty as "unknown" and simply omit the header.
  static String get installId => _installId;

  /// `android`, `ios`, `web`, … Read from Flutter rather than `dart:io` so the
  /// web build does not break on an unavailable `Platform`.
  static String get platform => kIsWeb ? 'web' : defaultTargetPlatform.name;

  /// Load the stored id, creating one on first launch.
  ///
  /// Resolved once at startup so every later request can read it synchronously
  /// and no call can race ahead of it.
  static Future<String> ensure() async {
    if (_installId.isNotEmpty) return _installId;
    try {
      final file = File('${(await getApplicationSupportDirectory()).path}/$_fileName');
      if (await file.exists()) {
        final stored = (await file.readAsString()).trim();
        if (stored.isNotEmpty) return _installId = stored;
      }
      final created = _randomId();
      await file.create(recursive: true);
      await file.writeAsString(created, flush: true);
      return _installId = created;
    } catch (_) {
      // No writable storage (web, a locked-down device, a full disk). Fall back
      // to a value that lasts for this session: analytics lose a little
      // accuracy, which is a far better outcome than blocking startup.
      return _installId = _randomId();
    }
  }

  /// Test seam.
  @visibleForTesting
  static void setForTesting(String value) => _installId = value;

  /// 32 hex characters from a cryptographic source — the shape of a UUID
  /// without taking on a package for it.
  static String _randomId() {
    final random = Random.secure();
    return List.generate(32, (_) => random.nextInt(16).toRadixString(16)).join();
  }
}
